
linters:
  enable-all: false
  enable:
    - deadcode
    - errcheck
    - goconst
    - gofmt
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - revive
    - structcheck
    - unconvert
    - varcheck
  disable:
    - lll
    - megacheck # Disabled due to OOM errors in golangci-lint@v1.18.0
    - staticcheck # Disabled due to OOM errors in golangci-lint@v1.18.0
run:
  skip-files:
  - schema.go
  skip-dirs:
  - provider/pkg/gen
  skip-dirs-use-default: true
  modules-download-mode: readonly
