// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package cluster

import (
	"context"
	"reflect"

	"github.com/frezbo/pulumi-provider-kind/sdk/v3/go/kind/networking"
	"github.com/frezbo/pulumi-provider-kind/sdk/v3/go/kind/node"
	"github.com/frezbo/pulumi-provider-kind/sdk/v3/go/kind/patchjson6902"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// KIND Cluster
type Cluster struct {
	pulumi.CustomResourceState

	ApiVersion                      pulumi.StringPtrOutput                     `pulumi:"apiVersion"`
	ContainerdConfigPatches         pulumi.StringArrayOutput                   `pulumi:"containerdConfigPatches"`
	ContainerdConfigPatchesJSON6902 pulumi.StringArrayOutput                   `pulumi:"containerdConfigPatchesJSON6902"`
	FeatureGates                    pulumi.StringMapOutput                     `pulumi:"featureGates"`
	Kind                            pulumi.StringPtrOutput                     `pulumi:"kind"`
	KubeadmConfigPatches            pulumi.StringArrayOutput                   `pulumi:"kubeadmConfigPatches"`
	KubeadmConfigPatchesJSON6902    patchjson6902.PatchJSON6902TypeArrayOutput `pulumi:"kubeadmConfigPatchesJSON6902"`
	Name                            pulumi.StringPtrOutput                     `pulumi:"name"`
	Networking                      networking.NetworkingTypePtrOutput         `pulumi:"networking"`
	Nodes                           node.NodeTypeArrayOutput                   `pulumi:"nodes"`
	RuntimeConfig                   pulumi.StringMapOutput                     `pulumi:"runtimeConfig"`
}

// NewCluster registers a new resource with the given unique name, arguments, and options.
func NewCluster(ctx *pulumi.Context,
	name string, args *ClusterArgs, opts ...pulumi.ResourceOption) (*Cluster, error) {
	if args == nil {
		args = &ClusterArgs{}
	}

	var resource Cluster
	err := ctx.RegisterResource("kind:Cluster:Cluster", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetCluster gets an existing Cluster resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetCluster(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ClusterState, opts ...pulumi.ResourceOption) (*Cluster, error) {
	var resource Cluster
	err := ctx.ReadResource("kind:Cluster:Cluster", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Cluster resources.
type clusterState struct {
	ApiVersion                      *string                           `pulumi:"apiVersion"`
	ContainerdConfigPatches         []string                          `pulumi:"containerdConfigPatches"`
	ContainerdConfigPatchesJSON6902 []string                          `pulumi:"containerdConfigPatchesJSON6902"`
	FeatureGates                    map[string]string                 `pulumi:"featureGates"`
	Kind                            *string                           `pulumi:"kind"`
	KubeadmConfigPatches            []string                          `pulumi:"kubeadmConfigPatches"`
	KubeadmConfigPatchesJSON6902    []patchjson6902.PatchJSON6902Type `pulumi:"kubeadmConfigPatchesJSON6902"`
	Name                            *string                           `pulumi:"name"`
	Networking                      *networking.NetworkingType        `pulumi:"networking"`
	Nodes                           []node.NodeType                   `pulumi:"nodes"`
	RuntimeConfig                   map[string]string                 `pulumi:"runtimeConfig"`
}

type ClusterState struct {
	ApiVersion                      pulumi.StringPtrInput
	ContainerdConfigPatches         pulumi.StringArrayInput
	ContainerdConfigPatchesJSON6902 pulumi.StringArrayInput
	FeatureGates                    pulumi.StringMapInput
	Kind                            pulumi.StringPtrInput
	KubeadmConfigPatches            pulumi.StringArrayInput
	KubeadmConfigPatchesJSON6902    patchjson6902.PatchJSON6902TypeArrayInput
	Name                            pulumi.StringPtrInput
	Networking                      networking.NetworkingTypePtrInput
	Nodes                           node.NodeTypeArrayInput
	RuntimeConfig                   pulumi.StringMapInput
}

func (ClusterState) ElementType() reflect.Type {
	return reflect.TypeOf((*clusterState)(nil)).Elem()
}

type clusterArgs struct {
	ApiVersion                      *string                           `pulumi:"apiVersion"`
	ContainerdConfigPatches         []string                          `pulumi:"containerdConfigPatches"`
	ContainerdConfigPatchesJSON6902 []string                          `pulumi:"containerdConfigPatchesJSON6902"`
	FeatureGates                    map[string]string                 `pulumi:"featureGates"`
	Kind                            *string                           `pulumi:"kind"`
	KubeadmConfigPatches            []string                          `pulumi:"kubeadmConfigPatches"`
	KubeadmConfigPatchesJSON6902    []patchjson6902.PatchJSON6902Type `pulumi:"kubeadmConfigPatchesJSON6902"`
	Name                            *string                           `pulumi:"name"`
	Networking                      *networking.NetworkingType        `pulumi:"networking"`
	Nodes                           []node.NodeType                   `pulumi:"nodes"`
	RuntimeConfig                   map[string]string                 `pulumi:"runtimeConfig"`
}

// The set of arguments for constructing a Cluster resource.
type ClusterArgs struct {
	ApiVersion                      pulumi.StringPtrInput
	ContainerdConfigPatches         pulumi.StringArrayInput
	ContainerdConfigPatchesJSON6902 pulumi.StringArrayInput
	FeatureGates                    pulumi.StringMapInput
	Kind                            pulumi.StringPtrInput
	KubeadmConfigPatches            pulumi.StringArrayInput
	KubeadmConfigPatchesJSON6902    patchjson6902.PatchJSON6902TypeArrayInput
	Name                            pulumi.StringPtrInput
	Networking                      networking.NetworkingTypePtrInput
	Nodes                           node.NodeTypeArrayInput
	RuntimeConfig                   pulumi.StringMapInput
}

func (ClusterArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*clusterArgs)(nil)).Elem()
}

type ClusterInput interface {
	pulumi.Input

	ToClusterOutput() ClusterOutput
	ToClusterOutputWithContext(ctx context.Context) ClusterOutput
}

func (*Cluster) ElementType() reflect.Type {
	return reflect.TypeOf((*Cluster)(nil))
}

func (i *Cluster) ToClusterOutput() ClusterOutput {
	return i.ToClusterOutputWithContext(context.Background())
}

func (i *Cluster) ToClusterOutputWithContext(ctx context.Context) ClusterOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ClusterOutput)
}

func (i *Cluster) ToClusterPtrOutput() ClusterPtrOutput {
	return i.ToClusterPtrOutputWithContext(context.Background())
}

func (i *Cluster) ToClusterPtrOutputWithContext(ctx context.Context) ClusterPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ClusterPtrOutput)
}

type ClusterPtrInput interface {
	pulumi.Input

	ToClusterPtrOutput() ClusterPtrOutput
	ToClusterPtrOutputWithContext(ctx context.Context) ClusterPtrOutput
}

type clusterPtrType ClusterArgs

func (*clusterPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**Cluster)(nil))
}

func (i *clusterPtrType) ToClusterPtrOutput() ClusterPtrOutput {
	return i.ToClusterPtrOutputWithContext(context.Background())
}

func (i *clusterPtrType) ToClusterPtrOutputWithContext(ctx context.Context) ClusterPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ClusterPtrOutput)
}

// ClusterArrayInput is an input type that accepts ClusterArray and ClusterArrayOutput values.
// You can construct a concrete instance of `ClusterArrayInput` via:
//
//          ClusterArray{ ClusterArgs{...} }
type ClusterArrayInput interface {
	pulumi.Input

	ToClusterArrayOutput() ClusterArrayOutput
	ToClusterArrayOutputWithContext(context.Context) ClusterArrayOutput
}

type ClusterArray []ClusterInput

func (ClusterArray) ElementType() reflect.Type {
	return reflect.TypeOf(([]*Cluster)(nil))
}

func (i ClusterArray) ToClusterArrayOutput() ClusterArrayOutput {
	return i.ToClusterArrayOutputWithContext(context.Background())
}

func (i ClusterArray) ToClusterArrayOutputWithContext(ctx context.Context) ClusterArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ClusterArrayOutput)
}

// ClusterMapInput is an input type that accepts ClusterMap and ClusterMapOutput values.
// You can construct a concrete instance of `ClusterMapInput` via:
//
//          ClusterMap{ "key": ClusterArgs{...} }
type ClusterMapInput interface {
	pulumi.Input

	ToClusterMapOutput() ClusterMapOutput
	ToClusterMapOutputWithContext(context.Context) ClusterMapOutput
}

type ClusterMap map[string]ClusterInput

func (ClusterMap) ElementType() reflect.Type {
	return reflect.TypeOf((map[string]*Cluster)(nil))
}

func (i ClusterMap) ToClusterMapOutput() ClusterMapOutput {
	return i.ToClusterMapOutputWithContext(context.Background())
}

func (i ClusterMap) ToClusterMapOutputWithContext(ctx context.Context) ClusterMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ClusterMapOutput)
}

type ClusterOutput struct {
	*pulumi.OutputState
}

func (ClusterOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Cluster)(nil))
}

func (o ClusterOutput) ToClusterOutput() ClusterOutput {
	return o
}

func (o ClusterOutput) ToClusterOutputWithContext(ctx context.Context) ClusterOutput {
	return o
}

func (o ClusterOutput) ToClusterPtrOutput() ClusterPtrOutput {
	return o.ToClusterPtrOutputWithContext(context.Background())
}

func (o ClusterOutput) ToClusterPtrOutputWithContext(ctx context.Context) ClusterPtrOutput {
	return o.ApplyT(func(v Cluster) *Cluster {
		return &v
	}).(ClusterPtrOutput)
}

type ClusterPtrOutput struct {
	*pulumi.OutputState
}

func (ClusterPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Cluster)(nil))
}

func (o ClusterPtrOutput) ToClusterPtrOutput() ClusterPtrOutput {
	return o
}

func (o ClusterPtrOutput) ToClusterPtrOutputWithContext(ctx context.Context) ClusterPtrOutput {
	return o
}

type ClusterArrayOutput struct{ *pulumi.OutputState }

func (ClusterArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]Cluster)(nil))
}

func (o ClusterArrayOutput) ToClusterArrayOutput() ClusterArrayOutput {
	return o
}

func (o ClusterArrayOutput) ToClusterArrayOutputWithContext(ctx context.Context) ClusterArrayOutput {
	return o
}

func (o ClusterArrayOutput) Index(i pulumi.IntInput) ClusterOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) Cluster {
		return vs[0].([]Cluster)[vs[1].(int)]
	}).(ClusterOutput)
}

type ClusterMapOutput struct{ *pulumi.OutputState }

func (ClusterMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]Cluster)(nil))
}

func (o ClusterMapOutput) ToClusterMapOutput() ClusterMapOutput {
	return o
}

func (o ClusterMapOutput) ToClusterMapOutputWithContext(ctx context.Context) ClusterMapOutput {
	return o
}

func (o ClusterMapOutput) MapIndex(k pulumi.StringInput) ClusterOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) Cluster {
		return vs[0].(map[string]Cluster)[vs[1].(string)]
	}).(ClusterOutput)
}

func init() {
	pulumi.RegisterOutputType(ClusterOutput{})
	pulumi.RegisterOutputType(ClusterPtrOutput{})
	pulumi.RegisterOutputType(ClusterArrayOutput{})
	pulumi.RegisterOutputType(ClusterMapOutput{})
}
