// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package cluster

import (
	"context"
	"reflect"

	mount "github.com/frezbo/pulumi-provider-kind/sdk/v3/go/kind/mount"
	networking "github.com/frezbo/pulumi-provider-kind/sdk/v3/go/kind/networking"
	node "github.com/frezbo/pulumi-provider-kind/sdk/v3/go/kind/node"
	patchjson6902 "github.com/frezbo/pulumi-provider-kind/sdk/v3/go/kind/patchjson6902"
	portmapping "github.com/frezbo/pulumi-provider-kind/sdk/v3/go/kind/portmapping"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// KIND Cluster
type ClusterType struct {
	ApiVersion                      *string                           `pulumi:"apiVersion"`
	ContainerdConfigPatches         []string                          `pulumi:"containerdConfigPatches"`
	ContainerdConfigPatchesJSON6902 []string                          `pulumi:"containerdConfigPatchesJSON6902"`
	FeatureGates                    map[string]string                 `pulumi:"featureGates"`
	Kind                            *string                           `pulumi:"kind"`
	KubeadmConfigPatches            []string                          `pulumi:"kubeadmConfigPatches"`
	KubeadmConfigPatchesJSON6902    []patchjson6902.PatchJSON6902Type `pulumi:"kubeadmConfigPatchesJSON6902"`
	Name                            *string                           `pulumi:"name"`
	Networking                      *networking.NetworkingType        `pulumi:"networking"`
	Nodes                           []node.NodeType                   `pulumi:"nodes"`
	RuntimeConfig                   map[string]string                 `pulumi:"runtimeConfig"`
}

// ClusterTypeInput is an input type that accepts ClusterTypeArgs and ClusterTypeOutput values.
// You can construct a concrete instance of `ClusterTypeInput` via:
//
//          ClusterTypeArgs{...}
type ClusterTypeInput interface {
	pulumi.Input

	ToClusterTypeOutput() ClusterTypeOutput
	ToClusterTypeOutputWithContext(context.Context) ClusterTypeOutput
}

// KIND Cluster
type ClusterTypeArgs struct {
	ApiVersion                      pulumi.StringPtrInput                     `pulumi:"apiVersion"`
	ContainerdConfigPatches         pulumi.StringArrayInput                   `pulumi:"containerdConfigPatches"`
	ContainerdConfigPatchesJSON6902 pulumi.StringArrayInput                   `pulumi:"containerdConfigPatchesJSON6902"`
	FeatureGates                    pulumi.StringMapInput                     `pulumi:"featureGates"`
	Kind                            pulumi.StringPtrInput                     `pulumi:"kind"`
	KubeadmConfigPatches            pulumi.StringArrayInput                   `pulumi:"kubeadmConfigPatches"`
	KubeadmConfigPatchesJSON6902    patchjson6902.PatchJSON6902TypeArrayInput `pulumi:"kubeadmConfigPatchesJSON6902"`
	Name                            pulumi.StringPtrInput                     `pulumi:"name"`
	Networking                      networking.NetworkingTypePtrInput         `pulumi:"networking"`
	Nodes                           node.NodeTypeArrayInput                   `pulumi:"nodes"`
	RuntimeConfig                   pulumi.StringMapInput                     `pulumi:"runtimeConfig"`
}

func (ClusterTypeArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ClusterType)(nil)).Elem()
}

func (i ClusterTypeArgs) ToClusterTypeOutput() ClusterTypeOutput {
	return i.ToClusterTypeOutputWithContext(context.Background())
}

func (i ClusterTypeArgs) ToClusterTypeOutputWithContext(ctx context.Context) ClusterTypeOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ClusterTypeOutput)
}

// KIND Cluster
type ClusterTypeOutput struct{ *pulumi.OutputState }

func (ClusterTypeOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ClusterType)(nil)).Elem()
}

func (o ClusterTypeOutput) ToClusterTypeOutput() ClusterTypeOutput {
	return o
}

func (o ClusterTypeOutput) ToClusterTypeOutputWithContext(ctx context.Context) ClusterTypeOutput {
	return o
}

func (o ClusterTypeOutput) ApiVersion() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ClusterType) *string { return v.ApiVersion }).(pulumi.StringPtrOutput)
}

func (o ClusterTypeOutput) ContainerdConfigPatches() pulumi.StringArrayOutput {
	return o.ApplyT(func(v ClusterType) []string { return v.ContainerdConfigPatches }).(pulumi.StringArrayOutput)
}

func (o ClusterTypeOutput) ContainerdConfigPatchesJSON6902() pulumi.StringArrayOutput {
	return o.ApplyT(func(v ClusterType) []string { return v.ContainerdConfigPatchesJSON6902 }).(pulumi.StringArrayOutput)
}

func (o ClusterTypeOutput) FeatureGates() pulumi.StringMapOutput {
	return o.ApplyT(func(v ClusterType) map[string]string { return v.FeatureGates }).(pulumi.StringMapOutput)
}

func (o ClusterTypeOutput) Kind() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ClusterType) *string { return v.Kind }).(pulumi.StringPtrOutput)
}

func (o ClusterTypeOutput) KubeadmConfigPatches() pulumi.StringArrayOutput {
	return o.ApplyT(func(v ClusterType) []string { return v.KubeadmConfigPatches }).(pulumi.StringArrayOutput)
}

func (o ClusterTypeOutput) KubeadmConfigPatchesJSON6902() patchjson6902.PatchJSON6902TypeArrayOutput {
	return o.ApplyT(func(v ClusterType) []patchjson6902.PatchJSON6902Type { return v.KubeadmConfigPatchesJSON6902 }).(patchjson6902.PatchJSON6902TypeArrayOutput)
}

func (o ClusterTypeOutput) Name() pulumi.StringPtrOutput {
	return o.ApplyT(func(v ClusterType) *string { return v.Name }).(pulumi.StringPtrOutput)
}

func (o ClusterTypeOutput) Networking() networking.NetworkingTypePtrOutput {
	return o.ApplyT(func(v ClusterType) *networking.NetworkingType { return v.Networking }).(networking.NetworkingTypePtrOutput)
}

func (o ClusterTypeOutput) Nodes() node.NodeTypeArrayOutput {
	return o.ApplyT(func(v ClusterType) []node.NodeType { return v.Nodes }).(node.NodeTypeArrayOutput)
}

func (o ClusterTypeOutput) RuntimeConfig() pulumi.StringMapOutput {
	return o.ApplyT(func(v ClusterType) map[string]string { return v.RuntimeConfig }).(pulumi.StringMapOutput)
}

func init() {
	pulumi.RegisterOutputType(ClusterTypeOutput{})
}
