// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * KIND PortMapping
 */
export class PortMapping extends pulumi.CustomResource {
    /**
     * Get an existing PortMapping resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): PortMapping {
        return new PortMapping(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kind:PortMapping:PortMapping';

    /**
     * Returns true if the given object is an instance of PortMapping.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is PortMapping {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === PortMapping.__pulumiType;
    }

    public readonly containerPort!: pulumi.Output<number | undefined>;
    public readonly hostPort!: pulumi.Output<number | undefined>;
    public readonly listenAddress!: pulumi.Output<string | undefined>;
    public readonly protocol!: pulumi.Output<string | undefined>;

    /**
     * Create a PortMapping resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: PortMappingArgs, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            inputs["containerPort"] = args ? args.containerPort : undefined;
            inputs["hostPort"] = args ? args.hostPort : undefined;
            inputs["listenAddress"] = args ? args.listenAddress : undefined;
            inputs["protocol"] = args ? args.protocol : undefined;
        } else {
            inputs["containerPort"] = undefined /*out*/;
            inputs["hostPort"] = undefined /*out*/;
            inputs["listenAddress"] = undefined /*out*/;
            inputs["protocol"] = undefined /*out*/;
        }
        if (!opts.version) {
            opts = pulumi.mergeOptions(opts, { version: utilities.getVersion()});
        }
        super(PortMapping.__pulumiType, name, inputs, opts);
    }
}

/**
 * The set of arguments for constructing a PortMapping resource.
 */
export interface PortMappingArgs {
    containerPort?: pulumi.Input<number>;
    hostPort?: pulumi.Input<number>;
    listenAddress?: pulumi.Input<string>;
    protocol?: pulumi.Input<string>;
}
