// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***


export const RoleType = {
    /**
     * node that hosts Kubernetes control-plane components
     */
    ControlPlane: "control-plane",
    /**
     * node that hosts Kubernetes worker
     */
    Worker: "worker",
    /**
     * node that hosts an external load balancer
     */
    LoadBalancer: "external-load-balancer",
} as const;

export type RoleType = (typeof RoleType)[keyof typeof RoleType];
