// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package networking

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// KIND Networking type
type Networking struct {
	ApiServerAddress  *string `pulumi:"apiServerAddress"`
	ApiServerPort     *int    `pulumi:"apiServerPort"`
	DisableDefaultCNI *bool   `pulumi:"disableDefaultCNI"`
	IpFamily          *string `pulumi:"ipFamily"`
	KubeProxyMode     *string `pulumi:"kubeProxyMode"`
	PodSubnet         *string `pulumi:"podSubnet"`
	ServiceSubnet     *string `pulumi:"serviceSubnet"`
}

// NetworkingInput is an input type that accepts NetworkingArgs and NetworkingOutput values.
// You can construct a concrete instance of `NetworkingInput` via:
//
//          NetworkingArgs{...}
type NetworkingInput interface {
	pulumi.Input

	ToNetworkingOutput() NetworkingOutput
	ToNetworkingOutputWithContext(context.Context) NetworkingOutput
}

// KIND Networking type
type NetworkingArgs struct {
	ApiServerAddress  pulumi.StringPtrInput `pulumi:"apiServerAddress"`
	ApiServerPort     pulumi.IntPtrInput    `pulumi:"apiServerPort"`
	DisableDefaultCNI pulumi.BoolPtrInput   `pulumi:"disableDefaultCNI"`
	IpFamily          pulumi.StringPtrInput `pulumi:"ipFamily"`
	KubeProxyMode     pulumi.StringPtrInput `pulumi:"kubeProxyMode"`
	PodSubnet         pulumi.StringPtrInput `pulumi:"podSubnet"`
	ServiceSubnet     pulumi.StringPtrInput `pulumi:"serviceSubnet"`
}

func (NetworkingArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*Networking)(nil)).Elem()
}

func (i NetworkingArgs) ToNetworkingOutput() NetworkingOutput {
	return i.ToNetworkingOutputWithContext(context.Background())
}

func (i NetworkingArgs) ToNetworkingOutputWithContext(ctx context.Context) NetworkingOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NetworkingOutput)
}

func (i NetworkingArgs) ToNetworkingPtrOutput() NetworkingPtrOutput {
	return i.ToNetworkingPtrOutputWithContext(context.Background())
}

func (i NetworkingArgs) ToNetworkingPtrOutputWithContext(ctx context.Context) NetworkingPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NetworkingOutput).ToNetworkingPtrOutputWithContext(ctx)
}

// NetworkingPtrInput is an input type that accepts NetworkingArgs, NetworkingPtr and NetworkingPtrOutput values.
// You can construct a concrete instance of `NetworkingPtrInput` via:
//
//          NetworkingArgs{...}
//
//  or:
//
//          nil
type NetworkingPtrInput interface {
	pulumi.Input

	ToNetworkingPtrOutput() NetworkingPtrOutput
	ToNetworkingPtrOutputWithContext(context.Context) NetworkingPtrOutput
}

type networkingPtrType NetworkingArgs

func NetworkingPtr(v *NetworkingArgs) NetworkingPtrInput {
	return (*networkingPtrType)(v)
}

func (*networkingPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**Networking)(nil)).Elem()
}

func (i *networkingPtrType) ToNetworkingPtrOutput() NetworkingPtrOutput {
	return i.ToNetworkingPtrOutputWithContext(context.Background())
}

func (i *networkingPtrType) ToNetworkingPtrOutputWithContext(ctx context.Context) NetworkingPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(NetworkingPtrOutput)
}

// KIND Networking type
type NetworkingOutput struct{ *pulumi.OutputState }

func (NetworkingOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Networking)(nil)).Elem()
}

func (o NetworkingOutput) ToNetworkingOutput() NetworkingOutput {
	return o
}

func (o NetworkingOutput) ToNetworkingOutputWithContext(ctx context.Context) NetworkingOutput {
	return o
}

func (o NetworkingOutput) ToNetworkingPtrOutput() NetworkingPtrOutput {
	return o.ToNetworkingPtrOutputWithContext(context.Background())
}

func (o NetworkingOutput) ToNetworkingPtrOutputWithContext(ctx context.Context) NetworkingPtrOutput {
	return o.ApplyT(func(v Networking) *Networking {
		return &v
	}).(NetworkingPtrOutput)
}
func (o NetworkingOutput) ApiServerAddress() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Networking) *string { return v.ApiServerAddress }).(pulumi.StringPtrOutput)
}

func (o NetworkingOutput) ApiServerPort() pulumi.IntPtrOutput {
	return o.ApplyT(func(v Networking) *int { return v.ApiServerPort }).(pulumi.IntPtrOutput)
}

func (o NetworkingOutput) DisableDefaultCNI() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v Networking) *bool { return v.DisableDefaultCNI }).(pulumi.BoolPtrOutput)
}

func (o NetworkingOutput) IpFamily() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Networking) *string { return v.IpFamily }).(pulumi.StringPtrOutput)
}

func (o NetworkingOutput) KubeProxyMode() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Networking) *string { return v.KubeProxyMode }).(pulumi.StringPtrOutput)
}

func (o NetworkingOutput) PodSubnet() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Networking) *string { return v.PodSubnet }).(pulumi.StringPtrOutput)
}

func (o NetworkingOutput) ServiceSubnet() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Networking) *string { return v.ServiceSubnet }).(pulumi.StringPtrOutput)
}

type NetworkingPtrOutput struct{ *pulumi.OutputState }

func (NetworkingPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Networking)(nil)).Elem()
}

func (o NetworkingPtrOutput) ToNetworkingPtrOutput() NetworkingPtrOutput {
	return o
}

func (o NetworkingPtrOutput) ToNetworkingPtrOutputWithContext(ctx context.Context) NetworkingPtrOutput {
	return o
}

func (o NetworkingPtrOutput) Elem() NetworkingOutput {
	return o.ApplyT(func(v *Networking) Networking { return *v }).(NetworkingOutput)
}

func (o NetworkingPtrOutput) ApiServerAddress() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Networking) *string {
		if v == nil {
			return nil
		}
		return v.ApiServerAddress
	}).(pulumi.StringPtrOutput)
}

func (o NetworkingPtrOutput) ApiServerPort() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Networking) *int {
		if v == nil {
			return nil
		}
		return v.ApiServerPort
	}).(pulumi.IntPtrOutput)
}

func (o NetworkingPtrOutput) DisableDefaultCNI() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Networking) *bool {
		if v == nil {
			return nil
		}
		return v.DisableDefaultCNI
	}).(pulumi.BoolPtrOutput)
}

func (o NetworkingPtrOutput) IpFamily() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Networking) *string {
		if v == nil {
			return nil
		}
		return v.IpFamily
	}).(pulumi.StringPtrOutput)
}

func (o NetworkingPtrOutput) KubeProxyMode() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Networking) *string {
		if v == nil {
			return nil
		}
		return v.KubeProxyMode
	}).(pulumi.StringPtrOutput)
}

func (o NetworkingPtrOutput) PodSubnet() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Networking) *string {
		if v == nil {
			return nil
		}
		return v.PodSubnet
	}).(pulumi.StringPtrOutput)
}

func (o NetworkingPtrOutput) ServiceSubnet() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Networking) *string {
		if v == nil {
			return nil
		}
		return v.ServiceSubnet
	}).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(NetworkingOutput{})
	pulumi.RegisterOutputType(NetworkingPtrOutput{})
}
