// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

/**
 * KIND Networking
 */
export class Networking extends pulumi.CustomResource {
    /**
     * Get an existing Networking resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Networking {
        return new Networking(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kind:Networking:Networking';

    /**
     * Returns true if the given object is an instance of Networking.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Networking {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Networking.__pulumiType;
    }

    public readonly apiServerAddress!: pulumi.Output<string | undefined>;
    public readonly apiServerPort!: pulumi.Output<number | undefined>;
    public readonly disableDefaultCNI!: pulumi.Output<boolean | undefined>;
    public readonly ipFamily!: pulumi.Output<string | undefined>;
    public readonly kubeProxyMode!: pulumi.Output<string | undefined>;
    public readonly podSubnet!: pulumi.Output<string | undefined>;
    public readonly serviceSubnet!: pulumi.Output<string | undefined>;

    /**
     * Create a Networking resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: NetworkingArgs, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            inputs["apiServerAddress"] = args ? args.apiServerAddress : undefined;
            inputs["apiServerPort"] = args ? args.apiServerPort : undefined;
            inputs["disableDefaultCNI"] = args ? args.disableDefaultCNI : undefined;
            inputs["ipFamily"] = args ? args.ipFamily : undefined;
            inputs["kubeProxyMode"] = args ? args.kubeProxyMode : undefined;
            inputs["podSubnet"] = args ? args.podSubnet : undefined;
            inputs["serviceSubnet"] = args ? args.serviceSubnet : undefined;
        } else {
            inputs["apiServerAddress"] = undefined /*out*/;
            inputs["apiServerPort"] = undefined /*out*/;
            inputs["disableDefaultCNI"] = undefined /*out*/;
            inputs["ipFamily"] = undefined /*out*/;
            inputs["kubeProxyMode"] = undefined /*out*/;
            inputs["podSubnet"] = undefined /*out*/;
            inputs["serviceSubnet"] = undefined /*out*/;
        }
        if (!opts.version) {
            opts = pulumi.mergeOptions(opts, { version: utilities.getVersion()});
        }
        super(Networking.__pulumiType, name, inputs, opts);
    }
}

/**
 * The set of arguments for constructing a Networking resource.
 */
export interface NetworkingArgs {
    apiServerAddress?: pulumi.Input<string>;
    apiServerPort?: pulumi.Input<number>;
    disableDefaultCNI?: pulumi.Input<boolean>;
    ipFamily?: pulumi.Input<string>;
    kubeProxyMode?: pulumi.Input<string>;
    podSubnet?: pulumi.Input<string>;
    serviceSubnet?: pulumi.Input<string>;
}
