// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package patchjson6902

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// KIND PatchJSON6902 type
type PatchJSON6902 struct {
	Group   *string `pulumi:"group"`
	Kind    *string `pulumi:"kind"`
	Patch   *string `pulumi:"patch"`
	Version *string `pulumi:"version"`
}

// PatchJSON6902Input is an input type that accepts PatchJSON6902Args and PatchJSON6902Output values.
// You can construct a concrete instance of `PatchJSON6902Input` via:
//
//          PatchJSON6902Args{...}
type PatchJSON6902Input interface {
	pulumi.Input

	ToPatchJSON6902Output() PatchJSON6902Output
	ToPatchJSON6902OutputWithContext(context.Context) PatchJSON6902Output
}

// KIND PatchJSON6902 type
type PatchJSON6902Args struct {
	Group   pulumi.StringPtrInput `pulumi:"group"`
	Kind    pulumi.StringPtrInput `pulumi:"kind"`
	Patch   pulumi.StringPtrInput `pulumi:"patch"`
	Version pulumi.StringPtrInput `pulumi:"version"`
}

func (PatchJSON6902Args) ElementType() reflect.Type {
	return reflect.TypeOf((*PatchJSON6902)(nil)).Elem()
}

func (i PatchJSON6902Args) ToPatchJSON6902Output() PatchJSON6902Output {
	return i.ToPatchJSON6902OutputWithContext(context.Background())
}

func (i PatchJSON6902Args) ToPatchJSON6902OutputWithContext(ctx context.Context) PatchJSON6902Output {
	return pulumi.ToOutputWithContext(ctx, i).(PatchJSON6902Output)
}

// PatchJSON6902ArrayInput is an input type that accepts PatchJSON6902Array and PatchJSON6902ArrayOutput values.
// You can construct a concrete instance of `PatchJSON6902ArrayInput` via:
//
//          PatchJSON6902Array{ PatchJSON6902Args{...} }
type PatchJSON6902ArrayInput interface {
	pulumi.Input

	ToPatchJSON6902ArrayOutput() PatchJSON6902ArrayOutput
	ToPatchJSON6902ArrayOutputWithContext(context.Context) PatchJSON6902ArrayOutput
}

type PatchJSON6902Array []PatchJSON6902Input

func (PatchJSON6902Array) ElementType() reflect.Type {
	return reflect.TypeOf((*[]PatchJSON6902)(nil)).Elem()
}

func (i PatchJSON6902Array) ToPatchJSON6902ArrayOutput() PatchJSON6902ArrayOutput {
	return i.ToPatchJSON6902ArrayOutputWithContext(context.Background())
}

func (i PatchJSON6902Array) ToPatchJSON6902ArrayOutputWithContext(ctx context.Context) PatchJSON6902ArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(PatchJSON6902ArrayOutput)
}

// KIND PatchJSON6902 type
type PatchJSON6902Output struct{ *pulumi.OutputState }

func (PatchJSON6902Output) ElementType() reflect.Type {
	return reflect.TypeOf((*PatchJSON6902)(nil)).Elem()
}

func (o PatchJSON6902Output) ToPatchJSON6902Output() PatchJSON6902Output {
	return o
}

func (o PatchJSON6902Output) ToPatchJSON6902OutputWithContext(ctx context.Context) PatchJSON6902Output {
	return o
}

func (o PatchJSON6902Output) Group() pulumi.StringPtrOutput {
	return o.ApplyT(func(v PatchJSON6902) *string { return v.Group }).(pulumi.StringPtrOutput)
}

func (o PatchJSON6902Output) Kind() pulumi.StringPtrOutput {
	return o.ApplyT(func(v PatchJSON6902) *string { return v.Kind }).(pulumi.StringPtrOutput)
}

func (o PatchJSON6902Output) Patch() pulumi.StringPtrOutput {
	return o.ApplyT(func(v PatchJSON6902) *string { return v.Patch }).(pulumi.StringPtrOutput)
}

func (o PatchJSON6902Output) Version() pulumi.StringPtrOutput {
	return o.ApplyT(func(v PatchJSON6902) *string { return v.Version }).(pulumi.StringPtrOutput)
}

type PatchJSON6902ArrayOutput struct{ *pulumi.OutputState }

func (PatchJSON6902ArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]PatchJSON6902)(nil)).Elem()
}

func (o PatchJSON6902ArrayOutput) ToPatchJSON6902ArrayOutput() PatchJSON6902ArrayOutput {
	return o
}

func (o PatchJSON6902ArrayOutput) ToPatchJSON6902ArrayOutputWithContext(ctx context.Context) PatchJSON6902ArrayOutput {
	return o
}

func (o PatchJSON6902ArrayOutput) Index(i pulumi.IntInput) PatchJSON6902Output {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) PatchJSON6902 {
		return vs[0].([]PatchJSON6902)[vs[1].(int)]
	}).(PatchJSON6902Output)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*PatchJSON6902Input)(nil)).Elem(), PatchJSON6902Args{})
	pulumi.RegisterInputType(reflect.TypeOf((*PatchJSON6902ArrayInput)(nil)).Elem(), PatchJSON6902Array{})
	pulumi.RegisterOutputType(PatchJSON6902Output{})
	pulumi.RegisterOutputType(PatchJSON6902ArrayOutput{})
}
