// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs, enums } from "../types";

export namespace mount {
    /**
     * KIND Mount type
     */
    export interface MountArgs {
        containerPath?: pulumi.Input<string>;
        hostPath?: pulumi.Input<string>;
        propagation?: pulumi.Input<string>;
        readOnly?: pulumi.Input<boolean>;
        selinuxRelabel?: pulumi.Input<boolean>;
    }
}

export namespace networking {
    /**
     * KIND Networking type
     */
    export interface NetworkingArgs {
        apiServerAddress?: pulumi.Input<string>;
        apiServerPort?: pulumi.Input<number>;
        disableDefaultCNI?: pulumi.Input<boolean>;
        ipFamily?: pulumi.Input<string>;
        kubeProxyMode?: pulumi.Input<string>;
        podSubnet?: pulumi.Input<string>;
        serviceSubnet?: pulumi.Input<string>;
    }
}

export namespace node {
    /**
     * KIND Node type
     */
    export interface NodeArgs {
        extraMounts?: pulumi.Input<pulumi.Input<inputs.mount.MountArgs>[]>;
        extraPortMappings?: pulumi.Input<pulumi.Input<inputs.portmapping.PortMappingArgs>[]>;
        image?: pulumi.Input<string>;
        kubeadmConfigPatches?: pulumi.Input<pulumi.Input<string>[]>;
        kubeadmConfigPatchesJSON6902?: pulumi.Input<pulumi.Input<inputs.patchjson6902.PatchJSON6902Args>[]>;
        labels?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
        /**
         * node role type
         */
        role?: pulumi.Input<string | enums.node.RoleType>;
    }
}

export namespace patchjson6902 {
    /**
     * KIND PatchJSON6902 type
     */
    export interface PatchJSON6902Args {
        group?: pulumi.Input<string>;
        kind?: pulumi.Input<string>;
        patch?: pulumi.Input<string>;
        version?: pulumi.Input<string>;
    }
}

export namespace portmapping {
    /**
     * KIND PortMapping type
     */
    export interface PortMappingArgs {
        containerPort?: pulumi.Input<number>;
        hostPort?: pulumi.Input<number>;
        listenAddress?: pulumi.Input<string>;
        protocol?: pulumi.Input<string>;
    }
}
