// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";

export namespace Cluster {
}

export namespace Mount {
    /**
     * KIND Mount
     */
    export interface MountArgs {
        containerPath?: pulumi.Input<string>;
        hostPath?: pulumi.Input<string>;
        propagation?: pulumi.Input<string>;
        readOnly?: pulumi.Input<boolean>;
        selinuxRelabel?: pulumi.Input<boolean>;
    }
}

export namespace Networking {
    /**
     * KIND Networking
     */
    export interface NetworkingArgs {
        apiServerAddress?: pulumi.Input<string>;
        apiServerPort?: pulumi.Input<number>;
        disableDefaultCNI?: pulumi.Input<boolean>;
        ipFamily?: pulumi.Input<string>;
        kubeProxyMode?: pulumi.Input<string>;
        podSubnet?: pulumi.Input<string>;
        serviceSubnet?: pulumi.Input<string>;
    }
}

export namespace Node {
    /**
     * KIND Node
     */
    export interface NodeArgs {
        extraMounts?: pulumi.Input<pulumi.Input<inputs.Mount.MountArgs>[]>;
        extraPortMappings?: pulumi.Input<pulumi.Input<inputs.PortMapping.PortMappingArgs>[]>;
        image?: pulumi.Input<string>;
        kubeadmConfigPatches?: pulumi.Input<pulumi.Input<string>[]>;
        kubeadmConfigPatchesJSON6902?: pulumi.Input<pulumi.Input<inputs.PatchJSON6902.PatchJSON6902Args>[]>;
        labels?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
        role?: pulumi.Input<string>;
    }
}

export namespace PatchJSON6902 {
    /**
     * KIND PatchJSON6902
     */
    export interface PatchJSON6902Args {
        group?: pulumi.Input<string>;
        kind?: pulumi.Input<string>;
        patch?: pulumi.Input<string>;
        version?: pulumi.Input<string>;
    }
}

export namespace PortMapping {
    /**
     * KIND PortMapping
     */
    export interface PortMappingArgs {
        containerPort?: pulumi.Input<number>;
        hostPort?: pulumi.Input<number>;
        listenAddress?: pulumi.Input<string>;
        protocol?: pulumi.Input<string>;
    }
}
