// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";

export namespace Cluster {
}

export namespace Mount {
    /**
     * KIND Mount
     */
    export interface Mount {
        containerPath?: string;
        hostPath?: string;
        propagation?: string;
        readOnly?: boolean;
        selinuxRelabel?: boolean;
    }
}

export namespace Networking {
    /**
     * KIND Networking
     */
    export interface Networking {
        apiServerAddress?: string;
        apiServerPort?: number;
        disableDefaultCNI?: boolean;
        ipFamily?: string;
        kubeProxyMode?: string;
        podSubnet?: string;
        serviceSubnet?: string;
    }
}

export namespace Node {
    /**
     * KIND Node
     */
    export interface Node {
        extraMounts?: outputs.Mount.Mount[];
        extraPortMappings?: outputs.PortMapping.PortMapping[];
        image?: string;
        kubeadmConfigPatches?: string[];
        kubeadmConfigPatchesJSON6902?: outputs.PatchJSON6902.PatchJSON6902[];
        labels?: {[key: string]: string};
        role?: string;
    }
}

export namespace PatchJSON6902 {
    /**
     * KIND PatchJSON6902
     */
    export interface PatchJSON6902 {
        group?: string;
        kind?: string;
        patch?: string;
        version?: string;
    }
}

export namespace PortMapping {
    /**
     * KIND PortMapping
     */
    export interface PortMapping {
        containerPort?: number;
        hostPort?: number;
        listenAddress?: string;
        protocol?: string;
    }
}
