// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs, enums } from "../types";

export namespace mount {
}

export namespace networking {
}

export namespace node {
}

export namespace patchjson6902 {
}

export namespace portmapping {
}
