// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

/**
 * KIND Node
 */
export class Node extends pulumi.CustomResource {
    /**
     * Get an existing Node resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Node {
        return new Node(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kind:index:Node';

    /**
     * Returns true if the given object is an instance of Node.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Node {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Node.__pulumiType;
    }


    /**
     * Create a Node resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: NodeArgs, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            inputs["extraMounts"] = args ? args.extraMounts : undefined;
            inputs["extraPortMappings"] = args ? args.extraPortMappings : undefined;
            inputs["image"] = args ? args.image : undefined;
            inputs["kubeadmConfigPatches"] = args ? args.kubeadmConfigPatches : undefined;
            inputs["kubeadmConfigPatchesJSON6902"] = args ? args.kubeadmConfigPatchesJSON6902 : undefined;
            inputs["labels"] = args ? args.labels : undefined;
            inputs["role"] = args ? args.role : undefined;
        } else {
        }
        if (!opts.version) {
            opts = pulumi.mergeOptions(opts, { version: utilities.getVersion()});
        }
        super(Node.__pulumiType, name, inputs, opts);
    }
}

/**
 * The set of arguments for constructing a Node resource.
 */
export interface NodeArgs {
    extraMounts?: pulumi.Input<pulumi.Input<inputs.MountArgs>[]>;
    extraPortMappings?: pulumi.Input<pulumi.Input<inputs.PortMappingArgs>[]>;
    image?: pulumi.Input<string>;
    kubeadmConfigPatches?: pulumi.Input<pulumi.Input<string>[]>;
    kubeadmConfigPatchesJSON6902?: pulumi.Input<pulumi.Input<inputs.PatchJSON6902Args>[]>;
    labels?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    role?: pulumi.Input<string>;
}
