// *** WARNING: this file was generated by pulumigen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * KIND PatchJSON6902
 */
export class PatchJSON6902 extends pulumi.CustomResource {
    /**
     * Get an existing PatchJSON6902 resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): PatchJSON6902 {
        return new PatchJSON6902(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kind:index:PatchJSON6902';

    /**
     * Returns true if the given object is an instance of PatchJSON6902.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is PatchJSON6902 {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === PatchJSON6902.__pulumiType;
    }


    /**
     * Create a PatchJSON6902 resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: PatchJSON6902Args, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.group === undefined) && !opts.urn) {
                throw new Error("Missing required property 'group'");
            }
            if ((!args || args.kind === undefined) && !opts.urn) {
                throw new Error("Missing required property 'kind'");
            }
            if ((!args || args.patch === undefined) && !opts.urn) {
                throw new Error("Missing required property 'patch'");
            }
            if ((!args || args.version === undefined) && !opts.urn) {
                throw new Error("Missing required property 'version'");
            }
            inputs["group"] = args ? args.group : undefined;
            inputs["kind"] = args ? args.kind : undefined;
            inputs["patch"] = args ? args.patch : undefined;
            inputs["version"] = args ? args.version : undefined;
        } else {
        }
        if (!opts.version) {
            opts = pulumi.mergeOptions(opts, { version: utilities.getVersion()});
        }
        super(PatchJSON6902.__pulumiType, name, inputs, opts);
    }
}

/**
 * The set of arguments for constructing a PatchJSON6902 resource.
 */
export interface PatchJSON6902Args {
    group: pulumi.Input<string>;
    kind: pulumi.Input<string>;
    patch: pulumi.Input<string>;
    version: pulumi.Input<string>;
}
